version: "3.9"

services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    volumes:
      - "./data-mysql1:data/db"