version: "3.9"

services:
    nginx-port1:
        image: nginx:latest
        container_name: nginx_port1
        ports:
            - protocol: tcp
              published: 8080
              target: 80
    nginx_port2:
        image: nginx:latest
        container_name: nginx_port2
        ports:
            - "8081:80"