version: "3.9"

services:
  mysql-example:
    image: mysql:latest
    container_name: mysql-example
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example